# Generated by Django 4.2.7 on 2023-11-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='company_url',
            field=models.URLField(blank=True),
        ),
    ]
