# Generated by Django 4.2.7 on 2023-11-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_workexperience_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(upload_to='skills'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.FileField(upload_to='socialmedia'),
        ),
    ]
