# Generated by Django 4.2.7 on 2023-11-20 20:45

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('massage', models.TextField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('short_description', models.TextField(max_length=500)),
                ('icon', models.ImageField(upload_to='icons')),
                ('color_primary', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#0a1647', 'black'), ('#ff4b1f', 'ORange'), ('#ff9068', 'ORangeLight'), ('#40c9ff', 'Sky'), ('#adfda2', 'Litegreen'), ('#e81cff', 'Purple'), ('#ffd200', 'Yellow'), ('#f7971e', 'Golden')])),
                ('color_secondary', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#0a1647', 'black'), ('#ff4b1f', 'ORange'), ('#ff9068', 'ORangeLight'), ('#40c9ff', 'Sky'), ('#adfda2', 'Litegreen'), ('#e81cff', 'Purple'), ('#ffd200', 'Yellow'), ('#f7971e', 'Golden')])),
                ('link', models.URLField(blank=True, default='mercegrower.com')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('percentage', models.IntegerField(blank=True, default=0)),
                ('image', models.ImageField(upload_to='skills')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=100)),
                ('icon', models.ImageField(upload_to='socialmedia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company_url', models.UUIDField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('logo', models.ImageField(upload_to='company-logo')),
                ('strock_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
