# Generated by Django 4.2.7 on 2023-11-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_skill_image_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
