# Generated by Django 4.2.7 on 2023-11-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_workexperience_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.FileField(upload_to='icons'),
        ),
    ]
