# Generated by Django 4.2.7 on 2023-11-26 21:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
