# Generated by Django 4.2.7 on 2023-12-02 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_workexperience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phoneNumber',
            field=models.CharField(default=8801632398271, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
